VAGRANTFILE_API_VERSION = "2"

$debs_install = <<SCRIPT
apt-get update -qq
apt-get install python-software-properties -y
add-apt-repository ppa:couchdb/stable -y
apt-get update -qq
apt-get install couchdb curl git -y
SCRIPT

$npm_install = <<SCRIPT
curl -sL https://deb.nodesource.com/setup_0.12 | bash -
apt-get install -y nodejs
SCRIPT

$hoodie_install = <<SCRIPT
npm install -g hoodie-cli
SCRIPT

$foundation_install = <<SCRIPT
npm install -g foundation-apps
npm install -g bower
npm install -g gulp
SCRIPT


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
    config.vm.define :vagrant do |vagrant|
        vagrant.vm.box = "ubuntu/trusty64"
        vagrant.vm.network "forwarded_port", guest: 4000, host:4000
        vagrant.vm.network "forwarded_port", guest: 4001, host:4001
        vagrant.vm.provision :shell, :inline => $debs_install
        vagrant.vm.provision :shell, :inline => $npm_install
        vagrant.vm.provision :shell, :inline => $hoodie_install
        vagrant.vm.provision :shell, :inline => $foundation_install
    end
end
